#!/usr/bin/env python
#coding=utf-8

__metaclass__ = type
class student:
    def __init__(self, name=None, age=0, s=[0]):
      
        self.name = name
        self.age = age
        self.s = s
    def get_name(self):
        if  23>self.age >=20:
            return 'zhangming'
        elif self.age >=23:
            return 'liqiang'
        else:
            return self.name
    def get_age(self):
        return self.age
  
    def get_max(self):
        return max(self.s)

xm = student('xiaoming',20,[69,88,100])
print xm.get_age()
print xm.get_name()
print xm.get_max()



dl = student('dalong',23,[82,60,99])
print dl.get_name()
print dl.get_age()
print dl.get_max()

